### ISSUE TITLE
gmxapi 0.0.5 should be more graceful with character encoding in work specification.

### ISSUE THREAD

**Issue by eirrgang** [kassonlab/gmxapi#119]
The serialized WorkSpec and WorkElement can end up with inconsistently placed "u" characters due to sloppy handling of character encoding in our Python code. #104 Illustrates that we should specify the character encoding even when not tied to specific media, such as a network protocol datagram or text file.

We need to

- [ ] enforce utf-8 encoding
- [ ] eliminate extraneous "u" string prefixes from artifacts of sloppy Python

**Comment by eirrgang** [comment]
We may want to restrict the character set for filenames to the `latin-1` character set for maximum compatibility. Suggestions? Schema 0.2 should probably specify a convention for platform-independent path representation and assert that path parameters will be converted to OS-appropriate formats and encodings by the Context.

**Comment by peterkasson** [comment]
Sounds good to me.

----------------------------------------------------------------------
Peter Kasson, MD, PhD
Associate Professor
Departments of Molecular Physiology and Biological Physics
and of Biomedical Engineering
University of Virginia
and
Program in Molecular Biophysics, Uppsala University
