### ISSUE TITLE
inconsistent gmx.Status and gmx.core.Status

### ISSUE THREAD

**Issue by eirrgang** [kassonlab/gmxapi#121]
We should probably encounter a consistent Status interface within the Python environment, and the way to do that is probably either to make gmx.core.Status inherit from gmx.Status or to import gmx.Status from gmx.core. In the former case, a two-way (but not necessarily circular) dependency is created with gmx and gmx.core. In the latter, we lose some readability and start to break down a wall that we tried to create between the pure Python and C++ extension components that maybe warrants reconsideration or additional discussion. Note that gmx.core is the Python bindings to the C++ libgmxapi and is intended to look like an idiomatic implementation of the same API.

Alternatively, we could completely rethink how status objects are created and used, since it was never really clear.

Off the top of my head it is unclear to me how or whether we can return gmx.Status or gmx.core.Status objects from external modules, such as restraint plugins, without making restraint plugins dependent on the gmx package. It may be acceptable that the Python interface for plugins is dependent on the gmx package if we can do so in a bindings-independent way, I think. If we do introduce a dependency, there is the question of whether the dependency is on the gmx pure Python module, or the gmx.core C++ extension module (core.so).

It may not be necessary for plugins to ever return a Status object, so more consideration is necessary.

**Comment by eirrgang** [comment]
The Pythonic thing to do would be to specify the interface for gmx.Status and not to require inheritance. Functionally, that is perfect for us, but my concern is that if a user runs a function or instance method (from gmx, gmx.core, or an external module) that returns a Status implementation, the doc string for that object should somehow be clearly connected to the specified gmx.Status interface. It should also be straight-forward for a developer to confirm that they have correctly implemented the Status interface for a given gmxapi spec.

Also, I don't know if other popular Python bindings frameworks have limitations on Python mix-ins, C++ extension classes inheriting from Python classes, etc, so there may be technical issues I haven't considered.

I think in the near term we should try to let uses of gmx.Status and gmx.core.Status depend only on the interface (attributes) rather than the class, and clarify that interface. This issue can stay open to continue discussion.

As a reminder, the specification of Status serves a few purposes.

1. Allow a proxy object to serve as a handle referring to the status of an operation that may not have executed yet to avoid forcing data flow resolution.
2. Potentially to serve as a container for exceptions or chains of exceptions (not implemented).
3. Provide a consistent abstraction across Python, C and C++ interfaces, which can have different conventional idioms for handling success or failure of different sorts of operations (e.g. boolean results, nullptr, None object, integer or enum error codes), avoiding ambiguity and unnecessary design/development constraints.

**Comment by eirrgang** [comment]
Here's an additional thought. Instead of each object owning a Status object that can be returned or having an inconsistent interface where functions either return an appropriate API object or a Status object, we could overload a `status` free function and/or converting constructors. Then we could more easily return dummy objects from unsuccessful operations.

This would require some rearchitecting. All classes that might be returned by functions that cross ABI boundaries (and shouldn't throw exceptions) would need to be interface classes whose implementation has a clear way to cast to Status, or with a member function pointer to determine whether the object is a dummy (with some error status) or not.

The point of this line of thought is to simplify the current interface style in which some functions return an object, some a pointer, some void, and some a Status object.

Yet another possibility is that all functions return a Status object and if there are additional results then they are held in the Status object or Context, but that would require run-time type information and I don't think we should go there.

**Comment by peterkasson** [comment]
How would this play with SIG handling?  Ideally we'd want each object to return something that reports successful/unsuccessful completion (potentially along with other things).  If unsuccessful completion, outputs would not be set.  (There might be a way to inspect the object, but it shouldn't set outputs and thus trigger downstream operations if unsuccessful completion.)

**Comment by eirrgang** [comment]
If the operation has been executed unsuccessfully, the status aspect of the output can be set without setting the other outputs, so that inspecting the Status would not retrigger execution. The second schema version will be explicit about the various inputs and outputs of each operation node, and I had been thinking about the status as being an implicit additional output, but maybe we should make it explicit, too.

**Comment by eirrgang** [comment]
In issue #125 @rolandschulz brought up `std::future` and asked about its suitability for this case. I offered [clarification](https://github.com/kassonlab/gmxapi/issues/125#issuecomment-417861416)

@mabraham [expands](https://github.com/kassonlab/gmxapi/issues/125#issuecomment-417991535):

> std::future is about asynchronous execution, but implies nothing about parallel execution. One can make a bunch of futures and never leave one's thread. So I echo Roland's question - I don't see the need for (or advantage of) a status object to query (which is just a fancy return code or global error variable, depending on the implementation).

It looks like an effective implementation for the proxied operations can use use `std::async` with `std::launch::deferred` launch policy to return a std::future with pretty much everything we should need. But I don't see how it follows that we don't need a Status object. In the case of operations that produce other API objects, std::future looks like the clear route to proxies to those results. In the case of operations that don't return any other results to the caller, though, we can either return a handle that I have been calling the Status object, or we could just return void, in which case we could either give up on direct API access to the result of the operation, or have a protocol for querying it from the Context or Session. But in order to be able to look it up, we'd need some sort of reference to the specific operation that was performed, and if we have that, it seems like we should be able to query it directly.

Then, maybe `success()` makes more sense as a free function that operates on a Status or any other API object to produce a boolean value, if that is all that is required.

**Comment by eirrgang** [comment]
Other things to think about to frame the question of whether/when to use exceptions versus status objects:

* Status state is expected to be part of the workflow checkpointing. I had assumed that exceptions would not be (unless they were packaged in something else, which I would implicitly tend to associate with the Status object).
* Transient errors are not part of a valid workflow state. Deterministic errors are the expected result of a work specification that was not capable of producing successful results.

**Comment by eirrgang** [comment]
This is a bit orthogonal, but to since parts of this conversation are about what is the API versus an implementation detail, it seems appropriate to bring up:

@peterkasson and I have talked about the need to make it very clear when a particular type of object access forces data flow resolution or for data to be made locally available / to cross the API boundary. I've been comfortable for a while with trying to use `extract()` to refer to such functions. I think `download()` is what leaps to many people's mind, but it isn't very general or accurate. `std::forward` uses `get()` but I don't think that has the desired built-in warning that "this function makes something happen right now" since we have accessors that don't. TensorFlow uses `evaluate()`, which seems pretty good when the only purpose is to cause execution, but the use case we're considering is generally going to be someone trying to access data, like to get a handle to an array or to get the boolean result of whether an operation was successful.

Thoughts?

**Comment by eirrgang** [comment]
Status objects are not used in gmxapi 0.1
