### ISSUE TITLE
map gmxapi C++ exceptions to Python gmx.exceptions

### ISSUE THREAD

**Issue by eirrgang** [kassonlab/gmxapi#125]
We need consistently defined exceptions in the C++ and Python gmxapi environments, and we need to be able to catch the C++ exceptions in Python as if they were gmx.exceptions exceptions. We might want to leave open the possibility that a `gmx` pure Python module can be imported without a `gmx.core` C++ extension. In that case, we need the primary exception classes to continue to be defined in `gmx/exceptions.py` and exported `gmxapi::Exception` subclasses should individually inherit from these.

Note: In Python, we need exceptions for syntax errors, usage errors, and some logic errors in order to "fail early" when the user attempts something impossible or that doesn't make sense. Otherwise, we would end up with situations like getting a None result, passing it to another command, getting a None result, passing it to another command, and getting a progressively uglier situation. (Also see "Effective Python" Items 14, 20.)

For API operations, though, that are abstracted for potentially deferred execution, exceptions are impossible, so we have to use the Status object (#121 ) or proxy objects that are clearly identifiable as representing a bad result.

The C++ API has the similar constraints, except that there are not keyword arguments with placeholder None / nullptr values to complicate things, and checking for nullptr results may seem preferable to try / catch blocks for the procedural interface.

For consistency and for the flexibility to have more varied and descriptive errors, I think that high level helper / utility / procedural functions mapping to the Python interface should throw "the same" exceptions as on the Python side whenever errors can be discovered immediately.

- [ ] register the gmxapi::Exception class and subclasses for export to gmx.core
- [ ] let gmx.core.Exception classes inherit from corresponding gmx.exceptions classes by importing pure Python module into gmx.core before exporting exceptions.
- [ ] reconcile a consistent set of exceptions.
- [ ] document error handling and exceptions policy
- [ ] update gmxapi src/gmx/test/test_exceptions.py

**Comment by rolandschulz** [comment]
Could you clarify "For API operations, though, that are abstracted for potentially deferred execution, exceptions are impossible, so we have to use the Status object (#121 ) or proxy objects that are clearly identifiable as representing a bad result."? Isn't that exactly what std::future does? Which works fine with exceptions. Or do you mean something different?

**Comment by eirrgang** [comment]
std::future could be part of the implementation, but I don't think it would be part of the API. I'm somewhat familiar with using std::future and other forms of that pattern for basic concurrency situations, but I don't have a clear picture of what the general case would look like. For one (probably just lack of experience), I don't know how a future on one MPI rank would deal with an exception on a different rank. Maybe it's easy, but I'm not familiar with it.

But our use case is more general in a few ways. To clarify the quote:

1. We don't want the "future" object that is exposed at the API level to be tied to any particular type of concurrency, but to make that an implementation detail of the Session in a given Context. It might refer to a result from an earlier process, a process that runs later, or a process that is dispatched through workflow management software to a remote environment.
2. The objects returned by API operations should not just be handles to results that are being calculated concurrently, but nodes in a data flow graph that is not necessarily executed until data flow constraints need to be satisfied. If a script doesn't need to examine an object directly (but may pass it to another object or operation), the work to produce the actual results can be deferred until a bundle of work can be dispatched together.

Obviously, this full abstraction is a few steps out. But that is all in reference to the API operation return objects. Regarding exceptions, I think they make the most sense for lower level operations that clearly occur locally in a consistent ABI environment. They can also be easily transformed to Python exceptions and are an easy way to handle generic unexpected situations that should have objects as return values (instead of just an error code or status object). So, yes, I think we can use exceptions in some cases, but I'm not sure if we can draw a firm line as to which those are. Part of the concern is technical, but I think the bigger concern is an easy-to-use API. So feedback on what feels comfortable and consistent in both C++ and Python is definitely appreciated.

**Comment by eirrgang** [comment]
@rolandschulz You mentioned off-line that you knew of some other tools that either offered or used a richer framework for some of these situations. Was that related to futures and exceptions? Would you mind pointing out some URLs?

**Comment by mabraham** [comment]
std::future is about asynchronous execution, but implies nothing about parallel execution. One can make a bunch of futures and never leave one's thread. So I echo Roland's question - I don't see the need for (or advantage of) a status object to query (which is just a fancy return code or global error variable, depending on the implementation).

MPI and exceptions is a bit of a red herring for us now, in that no real MPI runtimes have any non-trivial resiliency to error situations. But if one MPI rank threw an exception, and so was unavailable to contribute to a future awaited on another rank that needed an MPI operation that was now impossible, then it would be the job of the MPI runtime to propagate information about the failure to all affected ranks and that remote rank to e.g. throw within that future, which appears when it is waited upon.

Enqueuing a chunk of simulation and getting back a std::future<SimulationPart> is fine. If something failed, then it can throw when get() is called, or if it was only a partial failure, the methods of the returned SimulationPart can throw as needed.

**Comment by eirrgang** [comment]
I'm not sure if all of these comments are just in reference to the paragraph Roland quoted or the questions about exceptions-related questions in this issue. Maybe the distracting point is the word "impossible." If we wanted to, I suppose we could serialize exception objects to retrieve them from other processes or remote execution environments. But either the user would have to then extract an exception from some result object or potentially have to handle exceptions in weird places, possibly several at a time. I guess by "impossible," I mean that the usefulness of an exception to quickly indicate an unusual return situation is lost if the operation is not actually performed until several more API calls are made, or that some cases in which Python exceptions would typically be used do not map to meaningful exceptions for the same operations on the C++ side. 

> MPI and exceptions is a bit of a red herring for us now, in that no real MPI runtimes have any non-trivial resiliency to error situations. But if one MPI rank threw an exception, and so was unavailable to contribute to a future awaited on another rank that needed an MPI operation that was now impossible, then it would be the job of the MPI runtime to propagate information about the failure to all affected ranks and that remote rank to e.g. throw within that future, which appears when it is waited upon.

That sounds like a reason to avoid letting exceptions bubble to the top of any process. If the exception is not due to a memory error or something that indicates the computing resource is not fit to be reused by other work, shouldn't the exception be intercepted and turned into something else to send back to the scheduler and ultimately the API client? Should it be some wrapper from which to examine the exception or to rethrow it?

Part of the purpose of this issue is to discuss how and where to use exceptions. Some concrete examples might help.

* for cases above in which exceptions are the idiomatic Python way to handle a situation, how hard should we try to make the C++ side look similar, and vice versa, versus exploring unified alternatives to exceptions in those situations (in which case, what exceptions should we still provide and map, if any)?
* simulation is interrupted, as by SIGINT, and shuts itself down cleanly, but its work is not complete. How is this conveyed to the API client?
* in an ensemble of simulations, failures occur in some simulations, but useful work can still be performed. Should we throw exceptions, capture, and collect them, or should we express partial failures in a different way?
* a third-party package is connected to GROMACS with adapter code using a GROMACS extension interface.
  - Should exceptions be thrown from its own library to GROMACS?
  - From GROMACS to its own library?
  - What are the limitations on ABI compatibility in
    a. throwing exceptions from one compiled binary to another (the throw operation itself)
    b. the binary compatibility of classes derived from std::exception that are compiled in one bit of object code to be thrown in another

> Enqueuing a chunk of simulation and getting back a std::future is fine. If something failed, then it can throw when get() is called, or if it was only a partial failure, the methods of the returned SimulationPart can throw as needed.

This is true. Is this to say you suggest to maximize the use of exceptions as an error handling paradigm, where possible?

For the parts of the discussion related just to the implementation details of Status, I've copied and continued the discussion at https://github.com/kassonlab/gmxapi/issues/121#issuecomment-418160936

**Comment by eirrgang** [comment]
Should be resolved in gmxapi 0.1. If there are remaining problems, please report bugs through GROMACS issue tracking.
