### ISSUE TITLE
`steps` keyword argument has surprising/ambiguous behavior

### ISSUE THREAD

**Issue by eirrgang** [kassonlab/gmxapi#130]
Initial support for the `steps` keyword argument in `gmx.workflow.from_tpr()` has potentially surprising behavior (and will need to exhibit different behavior in the future as noted in #56 ).

Namely, _not_ specifying `steps` for a simulation that is using a previous simulation's output as input can result in a target step of _infinity_. (Note: for `gmx mdrun`, `-nsteps -1` is described as having this behavior, and only `-1`.) This is potentially more surprising to a user because `-cpi` is implicitly set for MD operations in gmxapi 0.0.6 in an attempt to have consistent behavior after an interruption and to make it easier to continue a trajectory in a 

I'm not sure if it is worth a complete resolution now, given longer-term plans. The workaround is to use a clean working directory, or at least to remove `state.cpt` and set `append=False`, and to be aware of the semantics.

- [x] improve documentation for `gmx.workflow.from_tpr()` `steps` keyword argument.

**Comment by peterkasson** [comment]
I think here we should replicate the normal mdrun behavior:  if -nsteps is not specified, it uses the number of steps in the TPR (counting a checkpoint restart as a continuation).  Appending or not doesn't affect this.  This should be the desired gmxapi behavior also.

**Comment by eirrgang** [comment]
I agree that unspecified steps should advance the trajectory to the point specified in the TPR file.

Right now it doesn't do that if there is a checkpoint that has gone past the step specified in the TPR file.

There are at least two cases, it seems, where the command line behavior can lead to infinite trajectories, and at least in the case described here, it seems like unintended behavior that could cause a user to accidentally burn up a lot of SUs, so I want to address this potentially surprising behavior and at least make sure it is well documented to disambiguate it a bit. I think this is achieved in https://github.com/kassonlab/gmxapi/pull/126/commits/2be078d70a50bdc9913d24adf8c661ac09983bdb

Setting an infinite number of steps could effectively be the way to replace the nsteps stop condition with some other, but it shouldn't be accidental the way it currently is.

I don't think this behavior is affected by whether or not appending is happening or not. I was thinking that appending could not be enabled for the workaround of removing the checkpoint file, but it may not be necessary to explicitly turn it off.

Note, though, that for automatic fault tolerance and reproducibility, we always restart from a checkpoint if one is found and we append to output files by default, but we don't have full workflow checkpointing yet, so these are implementation details that are very much open for discussion. But they are also likely to evolve naturally as we get better handling of simulation inputs and outputs, both with #79 and others. For more on appending / not appending to existing files, see #40 and https://github.com/kassonlab/gmxapi/pull/126

**Comment by eirrgang** [comment]
Several aspects of simulation continuation behavior were recently declared to be GROMACS bugs and behavior has changed in recent GROMACS patches. We need to check again that our behavior is sensible and accurately documented.

See, for example, https://gerrit.gromacs.org/c/8673/4 and https://gerrit.gromacs.org/c/8618/
