### ISSUE TITLE
Documentation needs updates for 0.0.7 release.

### ISSUE THREAD

**Issue by eirrgang** [kassonlab/gmxapi#177]
Various documentation updates are needed in the Sphinx RST documentation and in the embedded Python documentation.

**Comment by eirrgang** [comment]
- [ ] Remove hypothetical functionality documentation.
- [ ] Update version references and source code URLs
- [ ] Clarify GROMACS 2019, GROMACS master, and kassonlab/gromacs-gmxapi compatibility
- [ ] Update and simplify installation instructions
- [ ] Update change log, release notes
- [ ] Fix workflow syntax (gmx/workflow.py) and other sample code (reenable doctest?)
- [ ] Add link to Bioinformatics Applications note
- [ ] Add `doc` build target to `sample_restraint`?
- [ ] Update testing documentation re: tox versus pytest

**Comment by eirrgang** [comment]
We should probably also reserve `gmx` and/or `gmx-py` on PyPI...

**Comment by jmhays** [comment]
Minor point: can you remove the `$` from read the docs? Makes it easier for users to copy and paste code.

**Comment by eirrgang** [comment]
Do you mean the "prompt" character in all of the example snippets? Or a particular `$` somewhere?
