### ISSUE TITLE
Neural Net potential and py interface

### ISSUE THREAD

**Issue by FGMphys** [kassonlab/gmxapi#269]
Hi all,
It is possible to use a neural network potential in GROMACS, using the py interface for GROMACS?
FGM

**Comment by eirrgang** [comment]
The Python interface does not allow direct application of forces. It is intended to allow run-time binding of C++ code that interacts with the GROMACS ForceProvider interface.

There is no reason you couldn't call out to the Python interpreter or other API from a minimal C++ call-back. However, there is not currently a public API for GROMACS data locality, so there are potentially some caveats with respect to domain decomposition in MPI versus thread-MPI builds.

See also https://github.com/kassonlab/sample_restraint for sample code and https://pubs.acs.org/doi/10.1021/acs.jpclett.9b01407 for an application of an adaptive potential (self-training).

If you would like to discuss further, please email me or join me on Slack: https://join.slack.com/t/gmxapi/shared_invite/zt-p24he3rl-~Zt7X1jf7T8f8twUd2lj6w
