### ISSUE TITLE
Tool to update TPR

### ISSUE THREAD

**Issue by eirrgang** [kassonlab/gmxapi#86]
Ultimately, this also needs to be a workflow operation, but first we can just provide a Python tool. The use case is to create a new TPR from an existing TPR and checkpoint data for a (partially) executed simulation.

**Comment by eirrgang** [comment]
As described, this feature is not strictly possible in current GROMACS code. The TPR file does not include some state information that is in the checkpoint file. For the time being, this probably means we want to always use and manage checkpoint files through the gmxapi implementation so that we truly know what MD state we are dealing with and we can hide the pair of files (TPR and CPT) behind an API abstraction. :-\

Hopefully we can move quickly to an abstraction that does not specifically reference TPR files sooner than later, or these semantics will be confusing to users.

**Comment by peterkasson** [comment]
Important clarification:  modifying TPR settings (run input settings) is a needed near-term feature.  Modifying things in the MD simulation state (CPT file) is something entirely different and I don't think we want right now.

**Comment by eirrgang** [comment]
Yes, thank you. I should have just split this into two issues originally. The problem is that I mentioned "create a new TPR from an existing TPR" in the original description, but that is too different of a use case from "modify simulation input."

To clarify:

* modifying simulation input parameters is addressed in issue #85 
* manipulating and writing TPR files is the subject of this issue.
* manipulating microstate data that is currently split between checkpoint and TPR files is #70 , #71 , #94, #96, and probably others that have not yet been described.

As of this update, task #85 is "on deck" and task #86 is in limbo pending the sufficiency of the resolution to #85.
